

all: run

run: export LD_LIBRARY_PATH=/home/linuxbrew/.linuxbrew/lib
run: export PYENV_VERSION=spice
run:
	python main.py

# run:
# 	LD_LIBRARY_PATH=/home/linuxbrew/.linuxbrew/lib \
# 					PYENV_VERSION=spice \
# 					python main.py

clean:
	rm b3v33check.log
